metricsPort: 9092

sqs:
  region: us-east-1
  endpoint-override: http://localhost:4566
  credentials:
    access-key-id: 123
    secret-access-key: abc

database:
  host: localhost
  database: kstatus
  username: kstatus
  password: kstatus123

siteCheck:
  processors: 5
  sqs-queue-url: http://localhost:4566/000000000000/sqs-worker-inbox-queue